In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("student_performance.csv")

In [4]:
df.head()

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023
1,1002,Priya Patel,20,Female,Computer Science,2,76,82,88,79,87,Ahmedabad,2023
2,1003,Rohit Verma,19,Male,Electronics,2,65,74,61,55,78,Delhi,2023
3,1004,Sneha Reddy,20,Female,Mechanical,2,70,80,75,48,95,Hyderabad,2023
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023

In [5]:
df.tail()

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
25,1026,Rekha Nair,20,Female,Electronics,2,72,77,73,63,82,Kochi,2023
26,1027,Gaurav Shukla,21,Male,Computer Science,2,84,79,75,87,87,Lucknow,2023
27,1028,Sunita Pillai,19,Female,Civil,2,60,65,68,39,73,Thiruvananthapuram,2023
28,1029,Nitin Jain,20,Male,Mechanical,2,75,76,70,50,84,Indore,2023
29,1030,Akanksha Yadav,19,Female,Computer Science,2,91,93,87,94,95,Agra,2023

In [6]:
print(df.shape)
print(df.shape[0])#rows
print(df.shape[1])#columns

(30, 13)
30
13

In [7]:
print(df.dtypes)#data types

student_id                int64
name                     object
age                       int64
gender                   object
department               object
semester                  int64
math_score                int64
science_score             int64
english_score             int64
programming_score         int64
attendance_percentage     int64
city                     object
admission_year            int64
dtype: object

In [8]:
df.describe()

,student_id,age,semester,math_score,science_score,english_score,programming_score,attendance_percentage,admission_year
count,30.000000,30.000000,30.0,30.000000,30.000000,30.000000,30.000000,30.000000,30.0
mean,1015.500000,19.733333,2.0,76.066667,77.833333,74.166667,67.600000,84.500000,2023.0
std,8.803408,0.739680,0.0,11.467896,8.554423,10.003735,21.041175,9.379913,0.0
min,1001.000000,19.000000,2.0,56.000000,61.000000,55.000000,38.000000,65.000000,2023.0
25%,1008.250000,19.000000,2.0,67.250000,71.250000,67.250000,49.250000,77.250000,2023.0
50%,1015.500000,20.000000,2.0,75.500000,78.000000,75.000000,66.000000,86.500000,2023.0
75%,1022.750000,20.000000,2.0,85.750000,83.750000,81.750000,88.750000,91.750000,2023.0
max,1030.000000,21.000000,2.0,95.000000,93.000000,90.000000,97.000000,98.000000,2023.0

In [9]:
print(df.isnull().sum())

student_id               0
name                     0
age                      0
gender                   0
department               0
semester                 0
math_score               0
science_score            0
english_score            0
programming_score        0
attendance_percentage    0
city                     0
admission_year           0
dtype: int64

In [10]:
print(df['age'])

0     19
1     20
2     19
3     20
4     19
5     20
6     21
7     19
8     20
9     19
10    20
11    19
12    21
13    20
14    19
15    20
16    21
17    19
18    20
19    19
20    20
21    19
22    21
23    20
24    19
25    20
26    21
27    19
28    20
29    19
Name: age, dtype: int64

In [11]:
print(df['department'].unique())

['Computer Science' 'Electronics' 'Mechanical' 'Civil']

In [12]:
print(df['department'].value_counts())

department
Computer Science    13
Electronics          6
Mechanical           6
Civil                5
Name: count, dtype: int64

In [13]:
cs_students=df[df['department']=='Computer Science']
print(len(cs_students))

13

In [14]:
high_attendence=df[df['attendance_percentage']>90]
print(len(high_attendence))
print(high_attendence)

10
    student_id            name  age  gender        department  semester  \
0         1001    Aarav Sharma   19    Male  Computer Science         2
3         1004     Sneha Reddy   20  Female        Mechanical         2
7         1008     Divya Singh   19  Female  Computer Science         2
9         1010      Ananya Das   19  Female  Computer Science         2
13        1014   Kavya Nambiar   20  Female        Mechanical         2
15        1016    Ritu Agarwal   20  Female       Electronics         2
17        1018  Swati Kulkarni   19  Female  Computer Science         2
21        1022     Tanvi Mehta   19  Female  Computer Science         2
24        1025       Amit Bose   19    Male  Computer Science         2
29        1030  Akanksha Yadav   19  Female  Computer Science         2

    math_score  science_score  english_score  programming_score  \
0           85             78             72                 91
3           70             80             75                 48
7           88             91             84                 93
9           95             89             90                 97
13          74             78             82                 51
15          87             83             86                 69
17          90             87             85                 92
21          93             90             88                 96
24          86             82             79                 89
29          91             93             87                 94

    attendance_percentage       city  admission_year
0                      92     Mumbai            2023
3                      95  Hyderabad            2023
7                      96    Lucknow            2023
9                      98    Kolkata            2023
13                     91   Thrissur            2023
15                     93       Agra            2023
17                     94     Nagpur            2023
21                     97      Surat            2023
24                     91    Kolkata            2023
29                     95       Agra            2023

In [15]:
df['total_score']=df['math_score']+df['science_score']+df['programming_score']+df['english_score']

top_student=df.loc[df['total_score'].idxmax()]

print("Top student : ")
print(f"Name : {top_student['name']}")
print(f"Department : {top_student['department']}")
print(f"Total Score : {top_student['total_score']}")
print(f"Attendance : {top_student['attendance_percentage']}")

Top student :
Name : Ananya Das
Department : Computer Science
Total Score : 371
Attendance : 98

In [16]:
dept_avg=df.groupby('department')['total_score'].mean().round(2)
print("Avg total score by department:")
print(dept_avg)

Avg total score by department:
department
Civil               235.80
Computer Science    340.15
Electronics         277.50
Mechanical          267.33
Name: total_score, dtype: float64

In [17]:
df_sorted=df.sort_values(by='total_score',ascending=False)
print(df_sorted.head(10))

    student_id            name  age  gender        department  semester  \
9         1010      Ananya Das   19  Female  Computer Science         2
21        1022     Tanvi Mehta   19  Female  Computer Science         2
29        1030  Akanksha Yadav   19  Female  Computer Science         2
4         1005      Arjun Nair   19    Male  Computer Science         2
7         1008     Divya Singh   19  Female  Computer Science         2
17        1018  Swati Kulkarni   19  Female  Computer Science         2
24        1025       Amit Bose   19    Male  Computer Science         2
12        1013      Suresh Rao   21    Male  Computer Science         2
19        1020    Nisha Kapoor   19  Female  Computer Science         2
0         1001    Aarav Sharma   19    Male  Computer Science         2

    math_score  science_score  english_score  programming_score  \
9           95             89             90                 97
21          93             90             88                 96
29          91             93             87                 94
4           92             88             81                 95
7           88             91             84                 93
17          90             87             85                 92
24          86             82             79                 89
12          83             86             77                 88
19          79             84             81                 83
0           85             78             72                 91

    attendance_percentage        city  admission_year  total_score
9                      98     Kolkata            2023          371
21                     97       Surat            2023          367
29                     95        Agra            2023          365
4                      90       Kochi            2023          356
7                      96     Lucknow            2023          356
17                     94      Nagpur            2023          354
24                     91     Kolkata            2023          336
12                     88      Mysore            2023          334
19                     89  Chandigarh            2023          327
0                      92      Mumbai            2023          326

Question
1. How many students are from electronic department?
2. What is the averaage attendance of the female students?
3. who is the student with the lowest programming score?
4. how many students score above 80 in math?
5. What is the average total score for students with attendance above 90 percentage?

In [18]:
#How many students are from electronic department?
electronic_students=df[df['department']=='Electronics']
print(len(electronic_students))

6

In [19]:
#What is the averaage attendance of the female students?
female_students=df[df['gender']=='Female']
avg_attendance=female_students['attendance_percentage'].mean()
print(avg_attendance)

88.53333333333333

In [20]:
#who is the student with the lowest programming score?
lowest=df[df['programming_score']==df['programming_score'].min()]
print(lowest['name'])

16    Manoj Pandey
Name: name, dtype: object

In [21]:
#how many students score above 80 in math?
maths=df[df['math_score']>80]
print(len(maths))

11

In [22]:
#What is the average total score for students with attendance above 90 percentage?
above90=df[df['attendance_percentage']>90]
avg_above90=above90['total_score'].mean()
print(avg_above90)

335.8

# MINI PROJECT : Student Data Explorer
# Objective:

Create a Student Performance Explorer using Pandas and Pythin to analyze student data and generate a detailed report.

# Dataset Columns:

name

gender

department

math_score

programming_score

attendance_percentage

total_score

# Tasks to perform:
1. Display Project title

 Print a formatte title with seperator lines

2. Dataset Overview

Display:

-Total number of students

-total number of columns

-number of unique departments

3. Department wise analysis

display the count of students in each department.

4. Score Analysis

Find and Display:

-highest math score

-lowest math score

-avg math score

-avg programming score

-avg attendance percentage

5. Gender wise Analysis

Calculate and display avg total score by gender

6. Top performers

Display top 5 students based on total score.

Show:

-Student name

-Department

-total score

7. Attendance Analysis

Find students whose attendance is below 75%

Display:

-Name

-Department

-Atendance Percentage

If all students have attendance above 75%, print a suitable message.

# Concepts to use:

-pandas, DataFrame, groupby(), value_counts(), mean(), max(), min(), sort_values(), iterrows(), Conditional Statements, f-strings

In [35]:
print("="*40)
print("Student Performance Explorer")
print("="*40)
print()
print("-"*40)
print("Dataset Overview")
print("-"*40)
print("Total number of students=",len(df))
print("Total number of columns=",df.shape[1])
print("Number of unique departments=",df['department'].nunique())
print()
print("-"*40)
print("Department wise analysis")
print("-"*40)
print(df['department'].value_counts())
print()
print("-"*40)
print("Score Analysis")
print("-"*40)
print("highest math score=",df['math_score'].max())
print("lowest math score=",df['math_score'].min())
print("avg math score=",df['math_score'].mean())
print("avg programming score=",df['programming_score'].mean())
print("avg attendance percentage=",df['attendance_percentage'].mean())
print()
print("-"*40)
print("Gender wise Analysis")
print("-"*40)
female_students=df[df['gender']=='Female']
male_students=df[df['gender']=='Male']
print("avg total score of female students=",female_students['total_score'].mean())
print("avg total score of male students=",male_students['total_score'].mean())
print()
print("-"*40)
print("Top performers")
print("-"*40)
df_sorted=df.sort_values(by='total_score',ascending=False)
top=df_sorted.head(5)
print(f"{top['name']}{top['department']}{top['total_score']}")
print()
print("-"*40)
print("Attendance Analysis")
print("-"*40)
below_75=df[df['attendance_percentage']<75]
if len(below_75)==0:
    print("All students have attendance above 75%")
else:
    print(below_75[['name','department','attendance_percentage']])

========================================
Student Performance Explorer
========================================

----------------------------------------
Dataset Overview
----------------------------------------
Total number of students= 30
Total number of columns= 14
Number of unique departments= 4

----------------------------------------
Department wise analysis
----------------------------------------
department
Computer Science    13
Electronics          6
Mechanical           6
Civil                5
Name: count, dtype: int64

----------------------------------------
Score Analysis
----------------------------------------
highest math score= 95
lowest math score= 56
avg math score= 76.06666666666666
avg programming score= 67.6
avg attendance percentage= 84.5

----------------------------------------
Gender wise Analysis
----------------------------------------
avg total score of female students= 310.6666666666667
avg total score of male students= 280.6666666666667

----------------------------------------
Top performers
----------------------------------------
9         Ananya Das
21       Tanvi Mehta
29    Akanksha Yadav
4         Arjun Nair
7        Divya Singh
Name: name, dtype: object9     Computer Science
21    Computer Science
29    Computer Science
4     Computer Science
7     Computer Science
Name: department, dtype: object9     371
21    367
29    365
4     356
7     356
Name: total_score, dtype: int64

----------------------------------------
Attendance Analysis
----------------------------------------
             name   department  attendance_percentage
5     Meera Joshi  Electronics                     72
8    Rahul Mishra   Mechanical                     68
16   Manoj Pandey        Civil                     65
20  Harish Pillai  Electronics                     74
22   Sanjay Dubey        Civil                     70
27  Sunita Pillai        Civil                     73